spring:
  application:
    name: Journal Application

  data:
    mongodb:
      uri: mongodb+srv://AnkitAtlas:Learning2025@cluster0.yi12oix.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

    redis:
      host: localhost
      port: 6379

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitpanigrahi0@gmail.com
    password: xxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: ad7e47c5c483879c017c178f2722e8c9

quote:
  api:
    key: TZtQ3OBbGVTRdjlxrop/Nw==e2h22ZbnEQJ6AG3Q