spring:
  application:
    name: Journal Application

  data:
    mongodb:
      uri: mongodb+srv://AnkitAtlas:Learning2025@cluster0.yi12oix.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

    redis:
      host: redis-14046.c265.us-east-1-2.ec2.redns.redis-cloud.com
      port: 14046
      username: default
      password: PeFq3dMlfzdlZBdNluHudIapmVYZTxOd

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitpanigrahi0@gmail.com
    password: xxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
            json:
                trusted:
                  packages: "*"
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='57E7PTVK6AJIJ5VY' password='cflt9X4Gg5m6FJFQ5eI4+Nx5DllmXSeBNRrjy2K0hFtMK/k9gAmnSe1nBU9xKXfw';
      session:
        timeout:
          ms: 45000


server:
  port: 8080
  servlet:
    context-path: /journal

weather:
  api:
    key: ad7e47c5c483879c017c178f2722e8c9

quote:
  api:
    key: TZtQ3OBbGVTRdjlxrop/Nw==e2h22ZbnEQJ6AG3Q